// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {database} from '../models';
import {main} from '../models';
import {downloader} from '../models';
import {logger} from '../models';
import {config} from '../models';
import {metadata} from '../models';

export function CancelAllDownloads():Promise<void>;

export function CancelDownload(arg1:string):Promise<void>;

export function ClearCompletedDownloads():Promise<void>;

export function ClearLogs():Promise<void>;

export function ClearMetadataCache():Promise<number>;

export function DeleteDownloadRecord(arg1:string,arg2:boolean):Promise<void>;

export function DeleteServer(arg1:string):Promise<void>;

export function EnrichGameNow(arg1:number):Promise<database.GameEntity>;

export function ExportLogs(arg1:string):Promise<string>;

export function ExtractDominantColor(arg1:string):Promise<string>;

export function FindLinuxInstaller(arg1:string):Promise<string>;

export function GetAppInfo():Promise<main.AppInfo>;

export function GetCatalog(arg1:boolean):Promise<Array<database.GameEntity>>;

export function GetDiskSpaceInfo(arg1:string):Promise<main.DiskSpaceInfo>;

export function GetDownloadHistory():Promise<Array<database.DownloadRecord>>;

export function GetDownloads():Promise<Array<downloader.DownloadProgressEvent>>;

export function GetGameDetails(arg1:number):Promise<database.GameEntity>;

export function GetGameMovies(arg1:number):Promise<Array<database.SteamMovie>>;

export function GetGamePageDetails(arg1:number):Promise<main.GamePageDetails>;

export function GetLogs():Promise<Array<logger.LogEntry>>;

export function GetLogsText():Promise<string>;

export function GetSettings():Promise<config.AppSettings>;

export function GetStorageDrives():Promise<Array<downloader.StorageDriveInfo>>;

export function ImportFileZillaFile():Promise<Array<config.ServerConfig>>;

export function ImportFileZillaXML(arg1:string):Promise<Array<config.ServerConfig>>;

export function IsLinuxSystem():Promise<boolean>;

export function LaunchGame(arg1:string):Promise<void>;

export function LaunchGameByGameID(arg1:number):Promise<void>;

export function LaunchLinuxInstaller(arg1:string):Promise<void>;

export function LogMessage(arg1:string,arg2:string,arg3:string):Promise<void>;

export function OpenConfigFolder():Promise<void>;

export function OpenGameFolder(arg1:number):Promise<void>;

export function OpenLocalFolder(arg1:string):Promise<void>;

export function PauseAllDownloads():Promise<void>;

export function PauseDownload(arg1:string):Promise<void>;

export function ResetGameMetadata(arg1:number):Promise<void>;

export function ResolveGameBanner(arg1:number,arg2:string,arg3:number):Promise<string>;

export function ResolveGameCover(arg1:number,arg2:string,arg3:number):Promise<string>;

export function ResolveGameLogo(arg1:number,arg2:string,arg3:number):Promise<string>;

export function ResumeAllDownloads():Promise<void>;

export function ResumeDownload(arg1:string):Promise<void>;

export function SaveSettings(arg1:config.AppSettings):Promise<void>;

export function SearchSteam(arg1:string):Promise<Array<main.SteamSearchResult>>;

export function SearchSteamCandidates(arg1:string):Promise<Array<metadata.SteamCandidate>>;

export function SelectDirectory():Promise<string>;

export function SetActiveServer(arg1:string):Promise<void>;

export function StartDownload(arg1:number,arg2:string):Promise<string>;

export function TestConnection(arg1:config.ServerConfig):Promise<main.ConnectionTestResult>;

export function TriggerSteamOSKeyboard():Promise<void>;

export function UpdateSpeedLimit(arg1:number):Promise<void>;

export function UpdateSteamAppID(arg1:number,arg2:number):Promise<void>;

export function UpsertServer(arg1:config.ServerConfig):Promise<void>;
