// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddTorrentSource(arg1) {
  return window['go']['main']['App']['AddTorrentSource'](arg1);
}

export function CancelAllDownloads() {
  return window['go']['main']['App']['CancelAllDownloads']();
}

export function CancelDownload(arg1) {
  return window['go']['main']['App']['CancelDownload'](arg1);
}

export function ClearCompletedDownloads() {
  return window['go']['main']['App']['ClearCompletedDownloads']();
}

export function ClearLogs() {
  return window['go']['main']['App']['ClearLogs']();
}

export function ClearMetadataCache() {
  return window['go']['main']['App']['ClearMetadataCache']();
}

export function DeleteDownloadRecord(arg1, arg2) {
  return window['go']['main']['App']['DeleteDownloadRecord'](arg1, arg2);
}

export function DeleteServer(arg1) {
  return window['go']['main']['App']['DeleteServer'](arg1);
}

export function EnrichGameNow(arg1) {
  return window['go']['main']['App']['EnrichGameNow'](arg1);
}

export function ExportLogs(arg1) {
  return window['go']['main']['App']['ExportLogs'](arg1);
}

export function ExtractDominantColor(arg1) {
  return window['go']['main']['App']['ExtractDominantColor'](arg1);
}

export function FindLinuxInstaller(arg1) {
  return window['go']['main']['App']['FindLinuxInstaller'](arg1);
}

export function GetAppInfo() {
  return window['go']['main']['App']['GetAppInfo']();
}

export function GetCatalog(arg1) {
  return window['go']['main']['App']['GetCatalog'](arg1);
}

export function GetDiskSpaceInfo(arg1) {
  return window['go']['main']['App']['GetDiskSpaceInfo'](arg1);
}

export function GetDownloadHistory() {
  return window['go']['main']['App']['GetDownloadHistory']();
}

export function GetDownloads() {
  return window['go']['main']['App']['GetDownloads']();
}

export function GetFavorites() {
  return window['go']['main']['App']['GetFavorites']();
}

export function GetGameDetails(arg1) {
  return window['go']['main']['App']['GetGameDetails'](arg1);
}

export function GetGameMovies(arg1) {
  return window['go']['main']['App']['GetGameMovies'](arg1);
}

export function GetGamePageDetails(arg1) {
  return window['go']['main']['App']['GetGamePageDetails'](arg1);
}

export function GetLogs() {
  return window['go']['main']['App']['GetLogs']();
}

export function GetLogsText() {
  return window['go']['main']['App']['GetLogsText']();
}

export function GetMetadataProgress() {
  return window['go']['main']['App']['GetMetadataProgress']();
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function GetStorageDrives() {
  return window['go']['main']['App']['GetStorageDrives']();
}

export function GetTorrentCatalog(arg1) {
  return window['go']['main']['App']['GetTorrentCatalog'](arg1);
}

export function GetTorrentSources() {
  return window['go']['main']['App']['GetTorrentSources']();
}

export function ImportFileZillaFile() {
  return window['go']['main']['App']['ImportFileZillaFile']();
}

export function ImportFileZillaXML(arg1) {
  return window['go']['main']['App']['ImportFileZillaXML'](arg1);
}

export function ImportTorrentSourceFile() {
  return window['go']['main']['App']['ImportTorrentSourceFile']();
}

export function IsLinuxSystem() {
  return window['go']['main']['App']['IsLinuxSystem']();
}

export function LaunchGame(arg1) {
  return window['go']['main']['App']['LaunchGame'](arg1);
}

export function LaunchGameByGameID(arg1) {
  return window['go']['main']['App']['LaunchGameByGameID'](arg1);
}

export function LaunchLinuxInstaller(arg1) {
  return window['go']['main']['App']['LaunchLinuxInstaller'](arg1);
}

export function LogMessage(arg1, arg2, arg3) {
  return window['go']['main']['App']['LogMessage'](arg1, arg2, arg3);
}

export function OpenConfigFolder() {
  return window['go']['main']['App']['OpenConfigFolder']();
}

export function OpenGameFolder(arg1) {
  return window['go']['main']['App']['OpenGameFolder'](arg1);
}

export function OpenLocalFolder(arg1) {
  return window['go']['main']['App']['OpenLocalFolder'](arg1);
}

export function PauseAllDownloads() {
  return window['go']['main']['App']['PauseAllDownloads']();
}

export function PauseDownload(arg1) {
  return window['go']['main']['App']['PauseDownload'](arg1);
}

export function RemoveFromFavorites(arg1) {
  return window['go']['main']['App']['RemoveFromFavorites'](arg1);
}

export function RemoveTorrentSource(arg1) {
  return window['go']['main']['App']['RemoveTorrentSource'](arg1);
}

export function ResetGameMetadata(arg1) {
  return window['go']['main']['App']['ResetGameMetadata'](arg1);
}

export function ResolveGameBanner(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveGameBanner'](arg1, arg2, arg3);
}

export function ResolveGameCover(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveGameCover'](arg1, arg2, arg3);
}

export function ResolveGameLogo(arg1, arg2, arg3) {
  return window['go']['main']['App']['ResolveGameLogo'](arg1, arg2, arg3);
}

export function ResumeAllDownloads() {
  return window['go']['main']['App']['ResumeAllDownloads']();
}

export function ResumeDownload(arg1) {
  return window['go']['main']['App']['ResumeDownload'](arg1);
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function SearchSteam(arg1) {
  return window['go']['main']['App']['SearchSteam'](arg1);
}

export function SearchSteamCandidates(arg1) {
  return window['go']['main']['App']['SearchSteamCandidates'](arg1);
}

export function SelectDirectory() {
  return window['go']['main']['App']['SelectDirectory']();
}

export function SetActiveServer(arg1) {
  return window['go']['main']['App']['SetActiveServer'](arg1);
}

export function SetFavoriteStatus(arg1, arg2) {
  return window['go']['main']['App']['SetFavoriteStatus'](arg1, arg2);
}

export function StartDownload(arg1, arg2) {
  return window['go']['main']['App']['StartDownload'](arg1, arg2);
}

export function StartTorrentDownload(arg1, arg2) {
  return window['go']['main']['App']['StartTorrentDownload'](arg1, arg2);
}

export function SyncTorrentSources() {
  return window['go']['main']['App']['SyncTorrentSources']();
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function ToggleTorrentSource(arg1, arg2) {
  return window['go']['main']['App']['ToggleTorrentSource'](arg1, arg2);
}

export function TriggerSteamOSKeyboard() {
  return window['go']['main']['App']['TriggerSteamOSKeyboard']();
}

export function UpdateSpeedLimit(arg1) {
  return window['go']['main']['App']['UpdateSpeedLimit'](arg1);
}

export function UpdateSteamAppID(arg1, arg2) {
  return window['go']['main']['App']['UpdateSteamAppID'](arg1, arg2);
}

export function UpsertServer(arg1) {
  return window['go']['main']['App']['UpsertServer'](arg1);
}
